//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyApp_Book
    {
        public System.Guid Id { get; set; }
        public string BookName { get; set; }
        public string Author { get; set; }
        public Nullable<System.Guid> DataId { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<System.Guid> DeletedById { get; set; }
    }
}
