//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ArticleList
    {
        public System.Guid Id { get; set; }
        public string AritcleName { get; set; }
        public Nullable<System.Guid> AritcleAuthorId { get; set; }
        public Nullable<System.DateTime> WriteTime { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> ChildType { get; set; }
        public string SimpleText { get; set; }
        public Nullable<int> LookNum { get; set; }
        public Nullable<int> LikeNum { get; set; }
        public Nullable<int> CommentNum { get; set; }
    }
}
